services:
    database:
        image: 'mysql:8.0'
        healthcheck:
            test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "${MYSQL_USER:-user}", "-p${MYSQL_PASSWORD:-pass}" ]
            interval: 5s
            retries: 5
            start_period: 60s
            timeout: 10s
        environment:
            MYSQL_DATABASE: main
        env_file: .env.db.local
        ports:
            # To allow the host machine to access the ports below, modify the lines below.
            # For example, to allow the host to connect to port 3306 on the container, you would change
            # "3306" to "3306:3306". Where the first port is exposed to the host and the second is the container port.
            # See https://docs.docker.com/compose/compose-file/compose-file-v3/#ports for more information.
            - '3306'
    web:
        depends_on:
            database:
                condition: service_healthy
                restart: true
        build: .
        environment:
            DATABASE_USER: app
        env_file: .env.web.local
        command: sh -c "php bin/console doctrine:migrations:migrate --no-interaction --allow-no-migration && apache2-foreground"
        ports:
            - 8080:80
